#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

docker run ${1:="-it --rm  -p 8888:8888 -v $(dirname $(readlink -f $0))/oxidized:/home/oxidized/.config/oxidized"} oxidized/oxidized:latest ${@:2}
