#!/bin/bash

GIT_ROOT=`git rev-parse --show-superproject-working-tree --show-toplevel | head -1`
HOOK_NAME=`basename $0`
LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"

if [ -e $LOCAL_HOOK ]; then
  $LOCAL_HOOK $@ # exec both, local hook -> global hook
  # source $LOCAL_HOOK # exec only local if local hook exists
fi
