#!/bin/bash

source `dirname ${0}`/_local-hook-exec


##### secretlint #####
echo 'execute secretlint...'
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
# Secretlint all selected files
echo "$FILES" | xargs secretlint --maskSecrets
if [ $? -ne 0 ] ;then
    exit 1
fi
