
[[Snippets]]
  Description = "junos show virtual-chassis diagnostics optics power"
  Output = ""
  Tag = []
  command = "show virtual-chassis vc-port diagnostics optics match \"(fpc|vcp|Module voltage  |Receiver signal avarage|output power  |Module temperature  )\""

[[Snippets]]
  Description = "send syslog using nc"
  Output = ""
  Tag = []
  command = "while true; do echo \"<PRI=0> Mar 27 00:46:46 test-hoge test message\" | nc -v -w 1 <destination_ip=127.0.0.1> <port=5140>; sleep <interval=1>; done"
