#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

docker run ${1:="-it --rm  -p 3000:3000 -v $(dirname $(readlink -f $0))/grafana:/var/lib/grafana"} grafana/grafana-enterprise:latest -- ${@:2}
#docker run -it --rm  -p 3000:3000 -e “GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app” grafana/grafana-enterprise:latest
