#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

mkdir -p $HOME/.config/gcloud
docker run --rm -it \
  --workdir /root \
  -e CLOUDSDK_CONFIG=/root/.config/gcloud \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  -v $HOME/.kube:/root/.kube \
  -v $HOME/.ssh:/root/.ssh \
  $1 \
  google/cloud-sdk ${@:2}
